var files_dup =
[
    [ "allegro.h", "allegro_8h.html", null ],
    [ "allegroLib.c", "allegro_lib_8c.html", "allegro_lib_8c" ],
    [ "allegroLib.h", "allegro_lib_8h.html", "allegro_lib_8h" ],
    [ "animacion.c", "animacion_8c.html", "animacion_8c" ],
    [ "animacion.h", "animacion_8h.html", "animacion_8h" ],
    [ "audio.c", "audio_8c.html", "audio_8c" ],
    [ "audio.h", "audio_8h.html", "audio_8h" ],
    [ "configuracion.h", "configuracion_8h.html", "configuracion_8h" ],
    [ "data.c", "data_8c.html", "data_8c" ],
    [ "data.h", "data_8h.html", "data_8h" ],
    [ "disdrv.h", "disdrv_8h.html", "disdrv_8h" ],
    [ "entidades.c", "entidades_8c.html", "entidades_8c" ],
    [ "entidades.h", "entidades_8h.html", "entidades_8h" ],
    [ "fisica.c", "fisica_8c.html", "fisica_8c" ],
    [ "fisica.h", "fisica_8h.html", "fisica_8h" ],
    [ "gamelogic.c", "gamelogic_8c.html", "gamelogic_8c" ],
    [ "gamelogic.h", "gamelogic_8h.html", "gamelogic_8h" ],
    [ "IEvents.c", "_i_events_8c.html", "_i_events_8c" ],
    [ "IEvents.h", "_i_events_8h.html", "_i_events_8h" ],
    [ "joydrv.h", "joydrv_8h.html", "joydrv_8h" ],
    [ "level.c", "level_8c.html", "level_8c" ],
    [ "level.h", "level_8h.html", "level_8h" ],
    [ "main.c", "main_8c.html", "main_8c" ],
    [ "matiasBrosGame.h", "matias_bros_game_8h.html", "matias_bros_game_8h" ],
    [ "menu.c", "menu_8c.html", "menu_8c" ],
    [ "menu.h", "menu_8h.html", "menu_8h" ],
    [ "raspi.h", "raspi_8h.html", null ],
    [ "render.c", "render_8c.html", "render_8c" ],
    [ "render.h", "render_8h.html", "render_8h" ],
    [ "template.c", "template_8c.html", null ],
    [ "template.h", "template_8h.html", null ],
    [ "times.c", "times_8c.html", "times_8c" ],
    [ "times.h", "times_8h.html", "times_8h" ]
];